### ISSUE TITLE
Fails on require...

### ISSUE THREAD

**Issue by JESii** [amogil/rspec-deep-ignore-order-matcher#3]
I put the gem in my Gemfile; I did bundle install successfully. However, when I do
  require 'rspec-deep-ignore-order-matcher'
and when I run my spec I get:
rspec spec/test_spec.rb 
/Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-deep-ignore-order-matcher-0.0.3/lib/rspec-deep-ignore-order-matcher.rb:1:in `require': cannot load such file -- rspec (LoadError)
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-deep-ignore-order-matcher-0.0.3/lib/rspec-deep-ignore-order-matcher.rb:1:in `<top (required)>'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
	from /Users/jseidel/dev/testapps/planner/config/application.rb:16:in `<top (required)>'
	from /Users/jseidel/dev/testapps/planner/config/environment.rb:2:in `require'
	from /Users/jseidel/dev/testapps/planner/config/environment.rb:2:in `<top (required)>'
	from /Users/jseidel/dev/testapps/planner/spec/rails_helper.rb:3:in `require'
	from /Users/jseidel/dev/testapps/planner/spec/rails_helper.rb:3:in `<top (required)>'
	from /Users/jseidel/dev/testapps/planner/spec/test_spec.rb:1:in `require'
	from /Users/jseidel/dev/testapps/planner/spec/test_spec.rb:1:in `<top (required)>'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/bin/rspec:23:in `load'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/bin/rspec:23:in `<main>'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jseidel/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'

**Comment by amogil** [comment]
Hi,

May I see the whole Gemfile?

**Comment by amogil** [comment]
Probably, you have no "gem 'rspec'" line your Gemfile.

**Comment by JESii** [comment]
I have gem rspec_rails ne.ar the bottom..
```ruby
source 'https://rubygems.org'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use postgresql as the database for Active Record
# gem 'pg'
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# use ReactJS
gem 'react-rails'
gem 'sprockets-coffee-react'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end


gem 'haml-rails'
gem 'capybara'
group :development, :test do
  gem 'rspec-rails'
  gem 'rspec-deep-ignore-order-matcher'
end

**Comment by amogil** [comment]
OK, I've spotted the problem. As a workaround, you can add `gem 'rspec'` before `gem 'rspec-rails'` line in your Gemfile to solve the problem.

I will fix this problem soon.

**Comment by amogil** [comment]
Fixed in v.0.0.4

**Comment by JESii** [comment]
thanks!
